import { groupBetaProfileSchema } from '@dock/shared/dist/group-beta-admission.js';

// Public operator identity generated by the reviewed offline issuance command.
// A setup code or invitation can select this identity, never supply an endpoint/key.
export const publicGroupBetaProfile = groupBetaProfileSchema.parse({
  version: 1,
  serviceId: '67953452-54e3-4d75-a980-d6afb554c090',
  endpointId: '67953452-54e3-4d75-a980-d6afb554c090',
  origin: 'https://sciencewithagents-groups-67953452.oscarbarrera.workers.dev',
  keys: [
    {
      kid: '0f2ecdc5117a0f82',
      publicKey: '316f7f4306ae9d48a50f2e06b741f5a63a18b101f8368c6cc66b4c53e6e325ed',
      state: 'create+route',
    },
  ],
});
