/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=deployment/phone-worker.wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=PhoneWorkerEnv deployment/phone-worker.env.d.ts` (hash: 64718250e34de53c3e275223e3956ab0)
interface __BaseEnv_PhoneWorkerEnv {
  PAIRED_APP: Fetcher;
  PHONE_PUBLIC_ORIGIN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./phone-worker');
  }
  interface Env extends __BaseEnv_PhoneWorkerEnv {}
}
interface PhoneWorkerEnv extends __BaseEnv_PhoneWorkerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, 'PHONE_PUBLIC_ORIGIN'>> {}
}
