/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 305c984ce9e6790ee71aa917dc69e4b1)
interface __BaseEnv_Env {
  HOSTING_MODE: 'disabled';
  GROUP_SETUP_HASH: '';
  HOSTING_ORIGIN: '';
  HOSTING_APPROVAL_HASH: '';
  GROUPS: DurableObjectNamespace<import('./src/index').GroupMembership>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
    durableNamespaces: 'GroupMembership';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        'HOSTING_MODE' | 'GROUP_SETUP_HASH' | 'HOSTING_ORIGIN' | 'HOSTING_APPROVAL_HASH'
      >
    > {}
}
