/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 87043535dc73e20831d94d52a3be88bc)
interface __BaseEnv_Env {
  HOSTING_MODE: 'disabled';
  GROUP_SETUP_HASH: '';
  HOSTING_ORIGIN: '';
  HOSTING_APPROVAL_HASH: '';
  GROUP_BETA_SERVICE_ID: '';
  GROUP_BETA_KEYS: '';
  GROUPS: DurableObjectNamespace<import('./src/index').GroupMembership>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
    durableNamespaces: 'GroupMembership';
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'HOSTING_MODE'
        | 'GROUP_SETUP_HASH'
        | 'HOSTING_ORIGIN'
        | 'HOSTING_APPROVAL_HASH'
        | 'GROUP_BETA_SERVICE_ID'
        | 'GROUP_BETA_KEYS'
      >
    > {}
}
