import { z } from 'zod';
import { effortSchema, providerIdSchema } from './providers.js';
import { tokenCountsSchema } from './usage.js';

/**
 * Owner-editable Slurm submission review. A probabilistic pre-submission policy review,
 * not a cluster quota: native Slurm remains authoritative for limits and admission.
 */
const slurmName = z
  .string()
  .trim()
  .regex(/^[A-Za-z0-9][A-Za-z0-9._-]{0,99}$/, 'Use the native Slurm name.');
const nullableCount = z.number().int().positive().max(1_000_000).nullable();

/** Routine reviewer: Claude Sonnet by default, Terra or any exact pin when chosen explicitly. */
export const slurmReviewerChoiceSchema = z
  .object({
    provider: providerIdSchema,
    family: z
      .string()
      .trim()
      .min(1)
      .max(60)
      .regex(/^[a-zA-Z0-9][a-zA-Z0-9 ._-]*$/),
    model: z.string().trim().min(1).max(100).nullable(),
    effort: effortSchema.nullable(),
  })
  .strict();
export const slurmResourceExpectationsSchema = z
  .object({
    maxTimeMinutes: nullableCount,
    maxCpus: nullableCount,
    maxMemoryGb: z.number().positive().max(1_000_000).nullable(),
    maxGpus: z.number().int().nonnegative().max(10_000).nullable(),
    maxNodes: nullableCount,
    maxArrayTasks: nullableCount,
  })
  .strict();
export const slurmSubmissionPolicySchema = z
  .object({
    revision: z.number().int().nonnegative(),
    enabled: z.boolean(),
    /** Null until the owner confirms it. Never inferred from Slurm's default account. */
    confirmedAccount: slurmName.nullable(),
    additionalAccounts: z.array(slurmName).max(8),
    requireExplicitAccount: z.boolean(),
    defaultPartition: slurmName.nullable(),
    /** Empty means the owner set no partition restriction (site and native rules still apply). */
    allowedPartitions: z.array(slurmName).max(20),
    defaultQos: slurmName.nullable(),
    resources: slurmResourceExpectationsSchema,
    labRules: z.string().max(4000),
    /** Bundled or refreshed site-rule asset id, such as fasrc-cannon. */
    siteRules: z
      .string()
      .regex(/^[a-z0-9][a-z0-9-]{0,62}$/)
      .nullable(),
    reviewer: slurmReviewerChoiceSchema,
    evidenceMaxAgeMinutes: z.number().int().min(1).max(240),
    approvalValidMinutes: z.number().int().min(5).max(1440),
  })
  .strict();
export type SlurmSubmissionPolicy = z.infer<typeof slurmSubmissionPolicySchema>;
export const defaultSlurmSubmissionPolicy: SlurmSubmissionPolicy = {
  revision: 0,
  enabled: false,
  confirmedAccount: null,
  additionalAccounts: [],
  requireExplicitAccount: true,
  defaultPartition: null,
  allowedPartitions: [],
  defaultQos: null,
  resources: {
    maxTimeMinutes: null,
    maxCpus: null,
    maxMemoryGb: null,
    maxGpus: null,
    maxNodes: null,
    maxArrayTasks: null,
  },
  labRules: '',
  siteRules: null,
  reviewer: { provider: 'claude', family: 'sonnet', model: null, effort: null },
  evidenceMaxAgeMinutes: 30,
  approvalValidMinutes: 120,
};
export const slurmPolicySaveSchema = z.discriminatedUnion('scope', [
  z
    .object({
      scope: z.literal('global'),
      key: z.uuid(),
      expectedRevision: z.number().int().nonnegative(),
      policy: slurmSubmissionPolicySchema,
    })
    .strict(),
  z
    .object({
      scope: z.literal('project'),
      projectId: z.uuid(),
      key: z.uuid(),
      expectedRevision: z.number().int().nonnegative(),
      /** Null removes the override; the project then follows the global policy. */
      policy: slurmSubmissionPolicySchema.nullable(),
    })
    .strict(),
]);

export const slurmSubmissionKindSchema = z.enum(['sbatch', 'salloc', 'srun']);
export const slurmRequestedResourcesSchema = z
  .object({
    account: z.string().max(200).nullable(),
    partition: z.string().max(200).nullable(),
    qos: z.string().max(200).nullable(),
    time: z.string().max(200).nullable(),
    cpusPerTask: z.string().max(200).nullable(),
    ntasks: z.string().max(200).nullable(),
    nodes: z.string().max(200).nullable(),
    memory: z.string().max(200).nullable(),
    memoryPerCpu: z.string().max(200).nullable(),
    gpus: z.string().max(200).nullable(),
    array: z.string().max(200).nullable(),
    jobName: z.string().max(200).nullable(),
  })
  .strict();
export const slurmScriptSchema = z
  .object({
    path: z.string().max(1000).nullable(),
    /**
     * host-read: read by this host; remote-read: read now through the fixed reader for the
     * configured SSH alias; server: generated by this server; inline: --wrap/heredoc;
     * declared: supplied by an agent and NOT verifiable at use.
     */
    source: z.enum([
      'host-read',
      'remote-read',
      'server',
      'declared',
      'inline',
      'none',
      'unavailable',
    ]),
    sha256: z
      .string()
      .regex(/^[a-f0-9]{64}$/)
      .nullable(),
    bytes: z.number().int().nonnegative().nullable(),
    /** Bounded copy kept in private runtime data; omitted from list summaries. */
    content: z.string().max(65_536).nullable(),
    unavailableReason: z.string().max(300).nullable(),
  })
  .strict();
export const slurmInvocationSchema = z
  .object({
    kind: slurmSubmissionKindSchema,
    /** Arguments before the script (or all arguments for salloc/srun), bounded. */
    arguments: z.array(z.string().max(500)).max(64),
    scriptArguments: z.array(z.string().max(500)).max(64),
    script: slurmScriptSchema,
    requested: slurmRequestedResourcesSchema,
    /** A loop, xargs, variable or wrapper hides the exact submission from the host. */
    opaque: z.boolean(),
  })
  .strict();
export const slurmProposalSchema = z
  .object({
    command: z.string().min(1).max(8000),
    location: z.enum(['cluster-local', 'ssh']),
    sshAlias: z.string().max(200).nullable(),
    workingDirectory: z.string().max(1000).nullable(),
    invocations: z.array(slurmInvocationSchema).min(1).max(4),
    truncated: z.boolean(),
    purpose: z.string().max(1000).nullable(),
  })
  .strict();
export type SlurmProposal = z.infer<typeof slurmProposalSchema>;
export type SlurmInvocation = z.infer<typeof slurmInvocationSchema>;

export const slurmFindingSchema = z
  .object({
    severity: z.enum(['blocking', 'warning', 'note']),
    /** Which owner rule, site rule or native limit this concerns. */
    rule: z.string().trim().min(1).max(200),
    detail: z.string().trim().min(1).max(600),
    evidence: z.string().max(400),
  })
  .strict();
/** The only shape accepted from the reviewer model; anything else is a failed review. */
export const slurmAssessmentSchema = z
  .object({
    disposition: z.enum(['approve', 'revise', 'ask_owner']),
    summary: z.string().trim().min(1).max(600),
    findings: z.array(slurmFindingSchema).max(12),
    suggestedCorrection: z.string().max(2000).nullable(),
    uncertainty: z.string().max(600),
    evidenceUsed: z.array(z.string().max(200)).max(12),
  })
  .strict();
export type SlurmAssessment = z.infer<typeof slurmAssessmentSchema>;
export type SlurmFinding = z.infer<typeof slurmFindingSchema>;

export const slurmEvidenceSchema = z
  .object({
    state: z.enum(['fresh', 'stale', 'absent']),
    observedAt: z.string().datetime().nullable(),
    ageSeconds: z.number().int().nonnegative().nullable(),
    cluster: z.string().max(100).nullable(),
    message: z.string().max(400),
  })
  .strict();
export const slurmReviewStatusValueSchema = z.enum([
  'waiting_evidence',
  'queued',
  'running',
  'completed',
  'failed',
  'expired',
]);
export const slurmReviewSchema = z
  .object({
    id: z.uuid(),
    /** Durable request UUID (tool receipt, owner key, or hook-derived). */
    requestKey: z.string().max(200),
    origin: z.enum(['hook', 'tool', 'owner', 'server']),
    /** Local Store project, or the internal review project for a cluster-project subject. */
    projectId: z.uuid(),
    /** Execution identity that scopes reuse; cluster projects are not local Store projects. */
    subject: z
      .object({
        kind: z.enum(['local', 'cluster']),
        id: z.uuid(),
        name: z.string().max(200),
      })
      .strict(),
    /** exact: every script was read or generated by the host; unverified: agent-declared or opaque. */
    verification: z.enum(['exact', 'unverified']),
    agentId: z.uuid().nullable(),
    helperId: z.uuid().nullable(),
    attempt: z.number().int().min(1).max(20),
    proposal: slurmProposalSchema,
    hashes: z
      .object({
        content: z.string().regex(/^[a-f0-9]{64}$/),
        command: z.string().regex(/^[a-f0-9]{64}$/),
        policy: z.string().regex(/^[a-f0-9]{64}$/),
        subject: z.string().regex(/^[a-f0-9]{64}$/),
        evidence: z
          .string()
          .regex(/^[a-f0-9]{64}$/)
          .nullable(),
      })
      .strict(),
    policyScope: z.enum(['global', 'project']),
    policyRevision: z.number().int().nonnegative(),
    evidence: slurmEvidenceSchema,
    reviewer: z
      .object({
        provider: providerIdSchema,
        model: z.string().max(100).nullable(),
        effort: z.string().max(64),
        agentId: z.uuid().nullable(),
        runId: z.uuid().nullable(),
      })
      .strict()
      .nullable(),
    status: slurmReviewStatusValueSchema,
    disposition: z.enum(['approve', 'revise', 'ask_owner']).nullable(),
    assessment: slurmAssessmentSchema.nullable(),
    hostFindings: z.array(slurmFindingSchema).max(20),
    ownerDecision: z
      .object({
        decision: z.enum(['approve', 'reject']),
        note: z.string().max(1000),
        decidedAt: z.string().datetime(),
        /** Explicit owner override of the current-native-evidence requirement. */
        withoutCurrentEvidence: z.boolean(),
      })
      .strict()
      .nullable(),
    failure: z.string().max(600).nullable(),
    /** True only while policy scope/revision, fresh matching evidence and the deadline hold. */
    allowsSubmission: z.boolean(),
    validity: z
      .object({
        state: z.enum([
          'current',
          'not_approved',
          'rejected',
          'expired',
          'policy_changed',
          'evidence_unavailable',
          'evidence_changed',
        ]),
        message: z.string().max(400),
      })
      .strict(),
    message: z.string().max(2000),
    usage: tokenCountsSchema.nullable(),
    createdAt: z.string().datetime(),
    updatedAt: z.string().datetime(),
    completedAt: z.string().datetime().nullable(),
    approvalExpiresAt: z.string().datetime().nullable(),
    notifiedAt: z.string().datetime().nullable(),
  })
  .strict();
export type SlurmReview = z.infer<typeof slurmReviewSchema>;

/** Typed agent request. Omit command and send reviewId to read one saved result. */
export const slurmReviewToolSchema = z.union([
  z
    .object({
      command: z.string().trim().min(1).max(8000),
      scriptContent: z.string().max(65_536).optional(),
      scriptPath: z.string().trim().min(1).max(1000).optional(),
      workingDirectory: z.string().trim().min(1).max(1000).optional(),
      purpose: z.string().trim().min(1).max(1000).optional(),
    })
    .strict(),
  z.object({ reviewId: z.uuid() }).strict(),
]);
export const slurmReviewToolResultSchema = z
  .object({
    reviewId: z.uuid(),
    status: slurmReviewStatusValueSchema,
    disposition: z.enum(['approve', 'revise', 'ask_owner']).nullable(),
    allowsSubmission: z.boolean(),
    verification: z.enum(['exact', 'unverified']),
    findings: z.array(slurmFindingSchema).max(32),
    suggestedCorrection: z.string().max(2000).nullable(),
    message: z.string().max(2000),
  })
  .strict();
export type SlurmReviewToolResult = z.infer<typeof slurmReviewToolResultSchema>;
export const slurmOwnerReviewRequestSchema = z
  .object({
    key: z.uuid(),
    projectId: z.uuid(),
    command: z.string().trim().min(1).max(8000),
    scriptContent: z.string().max(65_536).optional(),
    scriptPath: z.string().trim().min(1).max(1000).optional(),
    workingDirectory: z.string().trim().min(1).max(1000).optional(),
    purpose: z.string().trim().min(1).max(1000).optional(),
  })
  .strict();
export const slurmOwnerDecisionSchema = z
  .object({
    key: z.uuid(),
    decision: z.enum(['approve', 'reject', 'retry']),
    note: z.string().trim().max(1000),
    /** Approve even when no fresh matching native reading exists; recorded on the review. */
    withoutCurrentEvidence: z.boolean().default(false),
  })
  .strict();

/** Owner-confirmed workspace setup, merged into the global submission policy in its transaction. */
export const slurmWorkspaceDefaultsSchema = z
  .object({
    key: z.string().min(1).max(200),
    alias: z.string().trim().min(1).max(63),
    workspaceRevision: z.number().int().nonnegative(),
    username: z.string().max(100).nullable(),
    account: z.string().max(100).nullable(),
    siteRules: z
      .string()
      .regex(/^[a-z0-9][a-z0-9-]{0,62}$/)
      .nullable(),
    development: z
      .object({
        partition: z.string().max(100).nullable(),
        qos: z.string().max(100).nullable(),
        cpus: z.number().int().min(1).max(128),
        memoryMb: z.number().int().min(512).max(1_048_576),
        timeMinutes: z.number().int().min(1).max(720),
        idleMinutes: z.number().int().min(1).max(120),
      })
      .strict(),
  })
  .strict();
export type SlurmWorkspaceDefaults = z.infer<typeof slurmWorkspaceDefaultsSchema>;
/** Server-generated development allocation; never browser-chosen paths or executables. */
export const slurmDevelopmentReviewRequestSchema = z
  .object({
    key: z.uuid(),
    clusterProjectId: z.uuid(),
    clusterProjectName: z.string().trim().min(1).max(200),
    purpose: z.string().trim().min(1).max(1000).optional(),
    command: z.string().trim().min(1).max(8000),
    script: z.string().min(1).max(65_536),
    workingDirectory: z.string().trim().min(1).max(1000).nullable(),
  })
  .strict();
export const slurmDevelopmentReviewResultSchema = z
  .object({
    reviewId: z.uuid(),
    status: slurmReviewStatusValueSchema,
    pending: z.boolean(),
    allowed: z.boolean(),
    disposition: z.enum(['approve', 'revise', 'ask_owner']).nullable(),
    message: z.string().max(2000),
  })
  .strict();
export type SlurmDevelopmentReviewResult = z.infer<typeof slurmDevelopmentReviewResultSchema>;
export const slurmSiteRuleSetSchema = z
  .object({
    id: z.string().max(63),
    title: z.string().max(200),
    retrievedAt: z.string().max(40).nullable(),
    sources: z.array(z.string().url()).max(12),
    origin: z.enum(['bundled', 'refreshed']),
  })
  .strict();
export const slurmReviewStatusSchema = z
  .object({
    policy: slurmSubmissionPolicySchema,
    siteRuleSets: z.array(slurmSiteRuleSetSchema).max(20),
    reviews: z.array(slurmReviewSchema).max(50),
    notice: z.string().max(1200),
  })
  .strict();
export type SlurmReviewStatus = z.infer<typeof slurmReviewStatusSchema>;
